### ISSUE TITLE
How can I use in a specific folder / monorepo

### ISSUE THREAD

**Issue by joelrozen-bbm** [jpb06/bump-package#40]
I want to run this on a dir other than ./ in my repo
working-dir is only compatible with run not uses - would you consider introducing an input to specify the path to the package.json?
Or is this possible already in another way?

**Comment by jpb06** [comment]
Hello.
Yes it can be done. adding an input `cwd` coud do, what do you think?

**Comment by jpb06** [comment]
https://github.com/jpb06/bump-package/pull/44

**Comment by jpb06** [comment]
Released as [https://github.com/jpb06/bump-package/releases/tag/bump-package%40v2.6.1](2.6.1).

Please let me if that resolves your use case.

**Comment by jpb06** [comment]
[2.6.2](https://github.com/jpb06/bump-package/releases/tag/v2.6.2).
